service:
  name: aws-nodejs-typescript

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-east-1

functions:
  createSmartPot:
    handler: endpoints/create-smartpot.main
    events:
      - http:
          method: get
          path: create
