service:
  name: smartpot

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-east-1

  iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DescribeTable
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
        Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  getSmartPot:
    handler: endpoints/get-smartpot.main
    events:
      - http:
          method: get
          path: smarpot/{potId}
  moisture:
    handler: endpoints/moisture.main
    events:
      - http:
          method: get
          path: smarpot/{potId}/moisture
      - http:
          method: put
          path: smarpot/{potId}/moisture
  watered:
    handler: endpoints/watered.main
    events:
      - http:
          method: get
          path: smarpot/{potId}/watered
      - http:
          method: put
          path: smarpot/{potId}/watered
